services:
  mysql:
    image: mysql:8.0
    container_name: mlflow_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mlflow_root_password
      MYSQL_DATABASE: mlflow_db
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mlflow_network
    restart: unless-stopped

  mlflow:
    image: python:3.10-slim
    container_name: mlflow_server
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_BACKEND_STORE_URI=mysql+pymysql://mlflow_user:mlflow_password@mysql:3306/mlflow_db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/mlruns
    volumes:
      - ./mlflow:/mlflow:rw
      - ./requirements_mlflow.txt:/requirements.txt
    networks:
      - mlflow_network
    restart: unless-stopped
    user: root
    working_dir: /mlflow
    command: >
      sh -c "
        pip install -r /requirements.txt &&
        mkdir -p /mlflow/mlruns &&
        chmod 777 -R /mlflow/mlruns &&
        mlflow server --backend-store-uri mysql+pymysql://mlflow_user:mlflow_password@mysql:3306/mlflow_db --default-artifact-root /mlflow/mlruns --host 0.0.0.0 --port 5001
      "

  # Optional: Adminer for database management
  adminer:
    image: adminer
    container_name: mlflow_adminer
    ports:
      - "8080:8080"
    networks:
      - mlflow_network
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  mlflow_network:
    driver: bridge 